### ISSUE TITLE
关于 Rime 配置文件的一些建议（

### ISSUE THREAD

**Issue by LufsX** [franci-e/misc#1]
仓库里面的 [build](https://github.com/franci-e/misc/tree/main/RRime/build)、[luna_pinyin.userdb](https://github.com/franci-e/misc/tree/main/RRime/luna_pinyin.userdb)、[luna_pinyin_simp.userdb](https://github.com/franci-e/misc/tree/main/RRime/luna_pinyin_simp.userdb) 和 [installation.yaml](https://github.com/franci-e/misc/blob/main/RRime/installation.yaml) 文件都是多余哒

build 里存档的文件在部署 Rime 时会根据配置自动生成，而 userdb 文件夹里面存放着你的个人词频（有泄漏个人隐私的风险），[installation.yaml](https://github.com/franci-e/misc/blob/main/RRime/installation.yaml) 则是你的安装时的信息

以及，引用别人的词库配置不需要把整个仓库都放进来，单单抓字典文件（就是你在 [luna_pinyin_simp.extended.dict.yaml](https://github.com/franci-e/misc/blob/main/RRime/luna_pinyin_simp.extended.dict.yaml) 的文件）过来就行勒

（逃～（

**Comment by abaiii** [comment]
（草 `LufsX` 老师来了（

学到力 现在就去改一改（

**Comment by LufsX** [comment]
我只是个刚毕业又善于使用搜索引擎的菜鸡而已，不是啥老师（受不起 2333🤣
